import IphoneTestImg from '../../assets/Images/testImg/Home.png'
import TabletTestImg from '../../assets/Images/testImg/BigBubble.png'

export const PDetails = [
    {
        number: '',
        projectName: '',
        projectDesc: '',
        projectType: '',
        technologies: [''],
        imgIphone: '',
        imgTablet: '',
        rateIphone: '',
        rateTablet: '',
        scaleIphone: '',
        scaleTablet: '',
    },
    {
        number: '01',
        projectName: 'Dream House',
        projectDesc: 'Webpage of construction company',
        projectType: 'WEB APP',
        technologies: ['React', 'Sass', 'JavaScript'],
        imgIphone: IphoneTestImg,
        imgTablet: TabletTestImg,
        rateIphone: 1.05,
        rateTablet: 1.5,
        scaleIphone: 0.8,
        scaleTablet: 0.75,
    },
    {
        number: '02',
        projectName: 'Snowboard Reunion',
        projectDesc: 'Event that have beautifull coutdown timer to reunion in Alpes',
        projectType: 'WEB APP',
        technologies: ['JavaScript', 'Bootstrap'],
        imgIphone: IphoneTestImg,
        imgTablet: TabletTestImg,
        rateIphone: 1.05,
        rateTablet: 1.5,
        scaleIphone: 0.8,
        scaleTablet: 0.75,
    },
    {
        number: '03',
        projectName: '3D woobeling cubes',
        projectDesc: 'Messing with @react-three/fiber library',
        projectType: '3D pages',
        technologies: ['@react-three/fiber', 'react-three/drei'],
        imgIphone: IphoneTestImg,
        imgTablet: TabletTestImg,
        rateIphone: 1.05,
        rateTablet: 1.5,
        scaleIphone: 0.8,
        scaleTablet: 0.75,
    },
    {
        number: '04',
        projectName: 'Portfolio',
        projectDesc: 'My own portfolio, which I am proud of and showing my progress with programming and UI design',
        projectType: 'WEB APP',
        technologies: ['React', 'Sass', 'JavaScript'],
        imgIphone: IphoneTestImg,
        imgTablet: TabletTestImg,
        rateIphone: 1.05,
        rateTablet: 1.5,
        scaleIphone: 0.8,
        scaleTablet: 0.75,
    },
    {
        number: '',
        projectName: '',
        projectDesc: '',
        projectType: '',
        technologies: [''],
        imgIphone: '',
        imgTablet: '',
        rateIphone: '',
        rateTablet: '',
        scaleIphone: '',
        scaleTablet: '',
    },
]